package com.sciz.server.infrastructure.config.database;

import jakarta.annotation.PostConstruct;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

/**
* 序列自动修复配置
* <p>
* 功能：应用启动时自动检查并修复所有表的自增序列
* 问题：数据迁移时手动指定了 id 值，导致序列的当前值小于表中最大的 id
* 解决：自动将序列的当前值设置为表中最大的 id 值
* <p>
* PostgreSQL IDENTITY 列说明：
* - PostgreSQL 使用 GENERATED BY DEFAULT AS IDENTITY 创建自增主键
* - 序列名称通过 pg_get_serial_sequence() 函数获取，不是简单的 表名_id_seq
* - 需要查询 information_schema.columns 找到所有 IDENTITY 列，然后获取对应的序列
*
* @author JiaWen.Wu
* @className SequenceAutoFixConfig
* @date 2025-12-25 14:00
*/
@Slf4j
@Component
@Order(1) // 确保在其他组件初始化之前执行
@ConditionalOnProperty(name = "app.sequence.auto-fix.enabled", havingValue = "true", matchIfMissing = true)
public class SequenceAutoFixConfig {

   private final JdbcTemplate jdbcTemplate;

   @Autowired
   public SequenceAutoFixConfig(JdbcTemplate jdbcTemplate) {
       this.jdbcTemplate = jdbcTemplate;
   }

   /**
    * 应用启动时自动修复序列
    */
   @PostConstruct
   public void autoFixSequences() {
       log.info("开始检查并修复数据库序列...");

       try {
           // 查询所有使用 IDENTITY 列的表和序列信息
           // PostgreSQL 使用 pg_get_serial_sequence() 获取 IDENTITY 列对应的序列名
           String sql = """
                   SELECT
                       t.table_name,
                       c.column_name,
                       pg_get_serial_sequence(t.table_schema || '.' || t.table_name, c.column_name) AS sequence_name
                   FROM information_schema.tables t
                   INNER JOIN information_schema.columns c
                       ON t.table_schema = c.table_schema
                       AND t.table_name = c.table_name
                   WHERE t.table_schema = 'public'
                     AND t.table_type = 'BASE TABLE'
                     AND c.is_identity = 'YES'
                     AND c.column_name = 'id'
                   ORDER BY t.table_name
                   """;

           List<Map<String, Object>> identityColumns = jdbcTemplate.queryForList(sql);

           if (identityColumns.isEmpty()) {
               log.info("未找到使用 IDENTITY 列的表");
               return;
           }

           int fixedCount = 0;
           int skippedCount = 0;
           int errorCount = 0;

           for (Map<String, Object> row : identityColumns) {
               String tableName = (String) row.get("table_name");
               String columnName = (String) row.get("column_name");
               String sequenceName = (String) row.get("sequence_name");

               if (sequenceName == null || sequenceName.isEmpty()) {
                   log.debug("跳过表 {}：未找到对应的序列", tableName);
                   skippedCount++;
                   continue;
               }

               try {
                   // 获取表中最大的 id 值（包括逻辑删除的数据）
                   // 使用参数化查询避免 SQL 注入（虽然表名来自系统表，但为安全起见）
                   String maxIdSql = String.format("SELECT COALESCE(MAX(%s), 0) FROM %s", columnName, tableName);
                   Long maxId = jdbcTemplate.queryForObject(maxIdSql, Long.class);

                   if (maxId == null || maxId == 0) {
                       log.debug("跳过序列 {}：表 {} 为空或最大 id 为 0", sequenceName, tableName);
                       skippedCount++;
                       continue;
                   }

                   // 获取序列的当前值（last_value 是序列已经分配的最大值）
                   // 序列名称可能包含 schema 前缀（如 public.sys_role_permission_id_seq）
                   String currentValueSql = String.format("SELECT last_value FROM %s", sequenceName);
                   Long currentValue = jdbcTemplate.queryForObject(currentValueSql, Long.class);

                   // 如果序列值小于最大 id，则修复
                   // 注意：setval 的第三个参数为 false 表示下次 nextval 返回 maxId + 1
                   // 如果为 true，则下次 nextval 返回 maxId
                   if (currentValue != null && currentValue < maxId) {
                       // 序列名称需要加引号，如果包含 schema，需要分别处理
                       String fixSql = String.format("SELECT setval('%s', %d, false)", sequenceName, maxId);
                       jdbcTemplate.queryForObject(fixSql, Long.class);
                       log.info("已修复序列: {} (表: {}, 列: {}, 原值: {}, 新值: {})",
                               sequenceName, tableName, columnName, currentValue, maxId);
                       fixedCount++;
                   } else {
                       log.debug("序列正常: {} (表: {}, 当前值: {}, 最大 id: {})",
                               sequenceName, tableName, currentValue, maxId);
                       skippedCount++;
                   }

               } catch (Exception e) {
                   log.warn("修复序列失败: {} (表: {}), 错误: {}", sequenceName, tableName, e.getMessage());
                   errorCount++;
               }
           }

           log.info("序列检查完成：修复 {} 个序列，跳过 {} 个序列，失败 {} 个序列", fixedCount, skippedCount, errorCount);

       } catch (Exception e) {
           log.error("自动修复序列时发生异常: {}", e.getMessage(), e);
       }
   }
}
