/*
 Navicat Premium Dump SQL

 Source Server         : postgres
 Source Server Type    : PostgreSQL
 Source Server Version : 160010 (160010)
 Source Host           : localhost:5432
 Source Catalog        : sci-z-college
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160010 (160010)
 File Encoding         : 65001

 Date: 08/12/2025 09:23:26
*/


-- ----------------------------
-- Table structure for dify_api_keys
-- ----------------------------
DROP TABLE IF EXISTS "public"."dify_api_keys";
CREATE TABLE "public"."dify_api_keys" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "user_id" int8 NOT NULL,
  "key_type" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "resource_id" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "api_key" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "key_name" varchar(200) COLLATE "pg_catalog"."default",
  "description" text COLLATE "pg_catalog"."default",
  "is_active" bool DEFAULT true,
  "created_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "updated_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "created_by" varchar(100) COLLATE "pg_catalog"."default",
  "updated_by" varchar(100) COLLATE "pg_catalog"."default",
  "deleted" int4 DEFAULT 0
)
;
COMMENT ON COLUMN "public"."dify_api_keys"."id" IS '主键ID，自增';
COMMENT ON COLUMN "public"."dify_api_keys"."user_id" IS '用户ID';
COMMENT ON COLUMN "public"."dify_api_keys"."key_type" IS '密钥类型：dataset(知识库密钥), workflow(工作流密钥)';
COMMENT ON COLUMN "public"."dify_api_keys"."resource_id" IS '资源ID（知识库ID或工作流ID）';
COMMENT ON COLUMN "public"."dify_api_keys"."api_key" IS 'API密钥';
COMMENT ON COLUMN "public"."dify_api_keys"."key_name" IS '密钥名称';
COMMENT ON COLUMN "public"."dify_api_keys"."description" IS '密钥描述';
COMMENT ON COLUMN "public"."dify_api_keys"."is_active" IS '是否激活：true=激活，false=禁用';
COMMENT ON COLUMN "public"."dify_api_keys"."created_time" IS '创建时间';
COMMENT ON COLUMN "public"."dify_api_keys"."updated_time" IS '更新时间';
COMMENT ON COLUMN "public"."dify_api_keys"."created_by" IS '创建人';
COMMENT ON COLUMN "public"."dify_api_keys"."updated_by" IS '更新人';
COMMENT ON COLUMN "public"."dify_api_keys"."deleted" IS '逻辑删除标识：0=未删除，1=已删除';
COMMENT ON TABLE "public"."dify_api_keys" IS 'Dify API 密钥管理表';

-- ----------------------------
-- Records of dify_api_keys
-- ----------------------------
INSERT INTO "public"."dify_api_keys" VALUES (1, 1, 'dataset', 'knowledge_base_001', 'dataset-MwOxGbIDhZmg6bUdHEid0rhX', '默认知识库密钥', '管理员默认知识库API密钥', 'f', '2025-11-03 07:17:26.157061', '2025-11-03 07:17:26.157061', 'system', NULL, 0);
INSERT INTO "public"."dify_api_keys" VALUES (6, 1, 'chatbot', '35766afb-ab07-438d-84ed-40054f72b17f', 'app-fL2Abrb566WzXiif06MK2BGB', 'chatbot_595a3f97-c903-40c2-9cfb-d8ef662e141e', 'testte', 'f', NULL, NULL, 'admin', 'admin', 0);
INSERT INTO "public"."dify_api_keys" VALUES (7, 1, 'file', 'work_file', 'app-PZbKcvauvZpUO4NR6xgpjhlB', NULL, NULL, 'f', '2025-11-18 06:58:25.650167', '2025-11-18 06:58:25.650167', NULL, NULL, 0);
INSERT INTO "public"."dify_api_keys" VALUES (2, 1, 'workflow', 'workflow_001', 'app-PZbKcvauvZpUO4NR6xgpjhlB', '文件处理工作流密钥', '管理员默认工作流API密钥', 'f', '2025-11-03 07:17:26.157061', '2025-11-03 07:19:31.727833', 'system', NULL, 0);
INSERT INTO "public"."dify_api_keys" VALUES (9, 1, 'workflow', 'workflow', 'app-TsSdGbD50r8fDt1shM3RBSMi', '测试南极科技报告生成工作流', '测试科技报告生成', 'f', NULL, NULL, NULL, NULL, 0);

-- ----------------------------
-- Auto increment value for dify_api_keys
-- ----------------------------
SELECT setval('"public"."dify_api_keys_id_seq"', 9, true);

-- ----------------------------
-- Indexes structure for table dify_api_keys
-- ----------------------------
CREATE INDEX "idx_dify_api_keys_deleted" ON "public"."dify_api_keys" USING btree (
  "deleted" "pg_catalog"."int4_ops" ASC NULLS LAST
);
CREATE INDEX "idx_dify_api_keys_is_active" ON "public"."dify_api_keys" USING btree (
  "is_active" "pg_catalog"."bool_ops" ASC NULLS LAST
);
CREATE INDEX "idx_dify_api_keys_key_type" ON "public"."dify_api_keys" USING btree (
  "key_type" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_dify_api_keys_resource_id" ON "public"."dify_api_keys" USING btree (
  "resource_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_dify_api_keys_user_id" ON "public"."dify_api_keys" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "uk_dify_api_keys_user_resource_type" ON "public"."dify_api_keys" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  "resource_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "key_type" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
