-- ******************************************************
-- Sci-Z Platform - Dify API Keys Table (PostgreSQL)
-- Purpose: Create dify_api_keys table for Dify API key management
-- Database: sciz_platform
-- Author: shihang.shang
-- Date: 2025-01-29
-- ******************************************************

-- 连接到数据库
\c sciz_platform;

BEGIN;

-- ===================== DIFY API KEYS TABLE =====================

CREATE TABLE IF NOT EXISTS dify_api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    key_type VARCHAR(50) NOT NULL,
    resource_id VARCHAR(100) NOT NULL,
    api_key VARCHAR(255) NOT NULL,
    key_name VARCHAR(200),
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    deleted INTEGER DEFAULT 0
);

-- 表注释
COMMENT ON TABLE dify_api_keys IS 'Dify API 密钥管理表';

-- 字段注释
COMMENT ON COLUMN dify_api_keys.id IS '主键ID，自增';
COMMENT ON COLUMN dify_api_keys.user_id IS '用户ID';
COMMENT ON COLUMN dify_api_keys.key_type IS '密钥类型：dataset(知识库密钥), workflow(工作流密钥)';
COMMENT ON COLUMN dify_api_keys.resource_id IS '资源ID（知识库ID或工作流ID）';
COMMENT ON COLUMN dify_api_keys.api_key IS 'API密钥';
COMMENT ON COLUMN dify_api_keys.key_name IS '密钥名称';
COMMENT ON COLUMN dify_api_keys.description IS '密钥描述';
COMMENT ON COLUMN dify_api_keys.is_active IS '是否激活：true=激活，false=禁用';
COMMENT ON COLUMN dify_api_keys.created_time IS '创建时间';
COMMENT ON COLUMN dify_api_keys.updated_time IS '更新时间';
COMMENT ON COLUMN dify_api_keys.created_by IS '创建人';
COMMENT ON COLUMN dify_api_keys.updated_by IS '更新人';
COMMENT ON COLUMN dify_api_keys.deleted IS '逻辑删除标识：0=未删除，1=已删除';

-- ===================== INDEXES =====================

-- 唯一索引：同一用户、同一资源、同一类型的密钥唯一
CREATE UNIQUE INDEX IF NOT EXISTS uk_dify_api_keys_user_resource_type 
    ON dify_api_keys(user_id, resource_id, key_type);

-- 普通索引：用户ID索引（用于按用户查询）
CREATE INDEX IF NOT EXISTS idx_dify_api_keys_user_id 
    ON dify_api_keys(user_id);

-- 普通索引：资源ID索引（用于按资源查询）
CREATE INDEX IF NOT EXISTS idx_dify_api_keys_resource_id 
    ON dify_api_keys(resource_id);

-- 普通索引：密钥类型索引（用于按类型查询）
CREATE INDEX IF NOT EXISTS idx_dify_api_keys_key_type 
    ON dify_api_keys(key_type);

-- 普通索引：激活状态索引（用于查询激活的密钥）
CREATE INDEX IF NOT EXISTS idx_dify_api_keys_is_active 
    ON dify_api_keys(is_active);

-- 普通索引：逻辑删除索引（用于过滤已删除记录）
CREATE INDEX IF NOT EXISTS idx_dify_api_keys_deleted 
    ON dify_api_keys(deleted);

-- ===================== TRIGGER FUNCTION =====================

-- 创建或替换触发器函数：自动更新 updated_time 字段
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_time = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

COMMENT ON FUNCTION update_updated_at_column() IS '自动更新 updated_time 字段的触发器函数';

-- ===================== TRIGGER =====================

-- 删除已存在的触发器（如果存在）
DROP TRIGGER IF EXISTS update_dify_api_keys_updated_time ON dify_api_keys;

-- 创建触发器：在更新记录时自动更新 updated_time
CREATE TRIGGER update_dify_api_keys_updated_time 
    BEFORE UPDATE ON dify_api_keys 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

COMMIT;

-- ===================== 示例数据（可选） =====================

-- 如果需要插入示例数据，可以取消下面的注释
/*
INSERT INTO dify_api_keys (user_id, key_type, resource_id, api_key, key_name, description, is_active, created_by, deleted)
VALUES 
    ('admin', 'dataset', 'knowledge_base_001', 'dataset-MwOxGbIDhZmg6bUdHEid0rhX', '默认知识库密钥', '管理员默认知识库API密钥', true, 'system', 0),
    ('admin', 'workflow', 'workflow_001', 'app-TsSdGbD50r8fDt1shM3RBSMi', '默认工作流密钥', '管理员默认工作流API密钥', true, 'system', 0)
ON CONFLICT (user_id, resource_id, key_type) DO NOTHING;
*/

