/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/Common/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/Common/BaseCard.vue')['default']
    BaseDialog: typeof import('./src/components/Common/BaseDialog.vue')['default']
    BasePagination: typeof import('./src/components/Common/BasePagination.vue')['default']
    BaseTable: typeof import('./src/components/Common/BaseTable.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    MainLayout: typeof import('./src/components/Layout/MainLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Layout/Sidebar.vue')['default']
  }
}
