/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButtons: typeof import('./src/components/Business/List/ActionButtons.vue')['default']
    AgreementNotice: typeof import('./src/components/Common/AgreementNotice.vue')['default']
    AttachmentList: typeof import('./src/components/Business/Detail/AttachmentList.vue')['default']
    BaseButton: typeof import('./src/components/Common/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/Common/BaseCard.vue')['default']
    BaseDialog: typeof import('./src/components/Common/BaseDialog.vue')['default']
    BasePagination: typeof import('./src/components/Common/BasePagination.vue')['default']
    BaseScrollbar: typeof import('./src/components/Common/BaseScrollbar.vue')['default']
    BaseTable: typeof import('./src/components/Common/BaseTable.vue')['default']
    ChartContainer: typeof import('./src/components/Business/Legacy/ChartContainer.vue')['default']
    DashboardStatCard: typeof import('./src/components/Business/Dashboard/DashboardStatCard.vue')['default']
    DataTable: typeof import('./src/components/Business/List/DataTable.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FileUpload: typeof import('./src/components/Business/Form/FileUpload.vue')['default']
    FormActions: typeof import('./src/components/Business/Form/FormActions.vue')['default']
    FormSection: typeof import('./src/components/Business/Form/FormSection.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    InfoCard: typeof import('./src/components/Business/Detail/InfoCard.vue')['default']
    LanguageSwitcher: typeof import('./src/components/Common/LanguageSwitcher.vue')['default']
    LoginForm: typeof import('./src/components/Business/Auth/LoginForm.vue')['default']
    MainLayout: typeof import('./src/components/Layout/MainLayout.vue')['default']
    ProgressBar: typeof import('./src/components/Business/Detail/ProgressBar.vue')['default']
    QuickActions: typeof import('./src/components/Business/Legacy/QuickActions.vue')['default']
    RecentActivity: typeof import('./src/components/Business/Legacy/RecentActivity.vue')['default']
    RegisterForm: typeof import('./src/components/Business/Auth/RegisterForm.vue')['default']
    ResetPasswordForm: typeof import('./src/components/Business/Auth/ResetPasswordForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/Business/List/SearchForm.vue')['default']
    Sidebar: typeof import('./src/components/Layout/Sidebar.vue')['default']
    StatCard: typeof import('./src/components/Business/Legacy/StatCard.vue')['default']
    StatusTag: typeof import('./src/components/Business/List/StatusTag.vue')['default']
    Timeline: typeof import('./src/components/Business/Detail/Timeline.vue')['default']
    UserProfile: typeof import('./src/components/Business/User/UserProfile.vue')['default']
    UserSecurity: typeof import('./src/components/Business/User/UserSecurity.vue')['default']
  }
}
