/*
 Navicat Premium Dump SQL

 Source Server         : postgres
 Source Server Type    : PostgreSQL
 Source Server Version : 160010 (160010)
 Source Host           : localhost:5432
 Source Catalog        : sci-z-college
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160010 (160010)
 File Encoding         : 65001

 Date: 24/12/2025 10:06:55
*/


-- ----------------------------
-- Table structure for sys_role_permission
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_role_permission";
CREATE TABLE "public"."sys_role_permission" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "role_id" int8 NOT NULL,
  "permission_id" int8 NOT NULL,
  "is_deleted" int2 DEFAULT 0,
  "created_by" int8,
  "updated_by" int8,
  "created_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "updated_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "public"."sys_role_permission"."id" IS '关联ID，主键，自增';
COMMENT ON COLUMN "public"."sys_role_permission"."role_id" IS '角色ID，关联sys_role表';
COMMENT ON COLUMN "public"."sys_role_permission"."permission_id" IS '权限ID，关联sys_permission表';
COMMENT ON COLUMN "public"."sys_role_permission"."is_deleted" IS '逻辑删除标识：0=未删除，1=已删除';
COMMENT ON COLUMN "public"."sys_role_permission"."created_time" IS '创建时间';
COMMENT ON TABLE "public"."sys_role_permission" IS '角色权限关联表';

-- ----------------------------
-- Records of sys_role_permission
-- ----------------------------
INSERT INTO "public"."sys_role_permission" VALUES (1, 1, 1, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (2, 1, 4, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (3, 1, 7, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (4, 1, 10, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (5, 1, 13, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (6, 1, 16, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (7, 1, 19, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (8, 1, 22, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (9, 1, 25, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (10, 1, 28, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (11, 1, 31, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (12, 1, 34, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (13, 1, 37, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (14, 1, 40, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (15, 1, 43, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (16, 1, 46, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (17, 1, 49, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (18, 1, 52, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (19, 1, 55, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (20, 1, 58, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (21, 1, 61, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (22, 1, 64, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (23, 1, 67, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (24, 1, 70, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (25, 1, 73, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (26, 1, 76, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (27, 1, 79, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (28, 1, 82, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (29, 1, 85, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (30, 1, 88, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (31, 1, 91, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (32, 1, 94, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (33, 1, 97, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (34, 1, 100, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (35, 1, 103, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (36, 4, 1, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (37, 4, 4, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (38, 4, 7, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (39, 4, 10, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (40, 4, 13, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (41, 4, 16, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (42, 4, 22, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (43, 4, 25, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (44, 4, 28, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (45, 4, 31, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (46, 4, 34, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (47, 4, 37, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (48, 4, 40, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (49, 4, 43, 0, NULL, NULL, '2025-11-11 05:13:15.757462', '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_role_permission" VALUES (50, 1, 106, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (51, 1, 109, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (52, 1, 112, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (53, 1, 115, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (54, 1, 118, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (55, 2, 107, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (56, 2, 110, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (57, 2, 113, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (58, 2, 116, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (59, 2, 119, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (60, 3, 108, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (61, 3, 111, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (62, 3, 114, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (63, 3, 117, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (64, 3, 120, 0, NULL, NULL, '2025-11-21 01:45:23.784258', '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_role_permission" VALUES (65, 1, 121, 1, NULL, NULL, '2025-11-25 03:40:45.387141', '2025-11-25 03:40:45.387141');
INSERT INTO "public"."sys_role_permission" VALUES (66, 1, 121, 1, NULL, NULL, '2025-11-25 05:10:27.429315', '2025-11-26 09:18:03.471459');
INSERT INTO "public"."sys_role_permission" VALUES (67, 4, 64, 0, NULL, NULL, '2025-11-26 09:19:08.336375', '2025-11-26 09:19:08.336375');
INSERT INTO "public"."sys_role_permission" VALUES (68, 4, 67, 0, NULL, NULL, '2025-11-26 09:19:08.336375', '2025-11-26 09:19:08.336375');
INSERT INTO "public"."sys_role_permission" VALUES (69, 4, 70, 0, NULL, NULL, '2025-11-26 09:19:08.336375', '2025-11-26 09:19:08.336375');
INSERT INTO "public"."sys_role_permission" VALUES (70, 4, 73, 0, NULL, NULL, '2025-11-26 09:19:08.336375', '2025-11-26 09:19:08.336375');
INSERT INTO "public"."sys_role_permission" VALUES (71, 4, 76, 0, NULL, NULL, '2025-11-26 09:19:08.336375', '2025-11-26 09:19:08.336375');
INSERT INTO "public"."sys_role_permission" VALUES (72, 4, 58, 0, NULL, NULL, '2025-11-26 09:19:08.336375', '2025-11-26 09:19:08.336375');
INSERT INTO "public"."sys_role_permission" VALUES (73, 4, 61, 0, NULL, NULL, '2025-11-26 09:19:08.336375', '2025-11-26 09:19:08.336375');
INSERT INTO "public"."sys_role_permission" VALUES (74, 1, 121, 0, NULL, NULL, '2025-12-05 11:07:27.132476', '2025-12-05 11:07:27.132476');
INSERT INTO "public"."sys_role_permission" VALUES (75, 1, 122, 1, NULL, NULL, '2025-12-16 08:17:15.400399', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (84, 4, 122, 1, NULL, NULL, '2025-12-16 08:17:15.400399', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (78, 2, 123, 1, NULL, NULL, '2025-12-16 08:17:15.400399', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (85, 5, 123, 1, NULL, NULL, '2025-12-16 08:17:15.400399', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (81, 3, 124, 1, NULL, NULL, '2025-12-16 08:17:15.400399', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (86, 6, 124, 1, NULL, NULL, '2025-12-16 08:17:15.400399', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (76, 1, 125, 1, NULL, NULL, '2025-12-16 08:17:15.400399', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (79, 2, 126, 1, NULL, NULL, '2025-12-16 08:17:15.400399', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (82, 3, 127, 1, NULL, NULL, '2025-12-16 08:17:15.400399', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (77, 1, 128, 1, NULL, NULL, '2025-12-16 08:17:15.400399', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (80, 2, 129, 1, NULL, NULL, '2025-12-16 08:17:15.400399', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (83, 3, 130, 1, NULL, NULL, '2025-12-16 08:17:15.400399', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (87, 1, 131, 0, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (91, 2, 132, 0, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (95, 3, 133, 0, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (88, 1, 134, 1, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_role_permission" VALUES (92, 2, 135, 1, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_role_permission" VALUES (89, 1, 137, 1, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_role_permission" VALUES (93, 2, 138, 1, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_role_permission" VALUES (90, 1, 140, 1, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_role_permission" VALUES (94, 2, 141, 1, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_role_permission" VALUES (99, 4, 131, 0, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (101, 5, 132, 0, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (103, 6, 133, 0, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_role_permission" VALUES (100, 4, 134, 1, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_role_permission" VALUES (102, 5, 135, 1, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_role_permission" VALUES (96, 3, 136, 1, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_role_permission" VALUES (104, 6, 136, 1, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_role_permission" VALUES (97, 3, 139, 1, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_role_permission" VALUES (98, 3, 142, 1, NULL, NULL, '2025-12-17 03:28:26.625994', '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_role_permission" VALUES (105, 1, 143, 1, NULL, NULL, '2025-12-17 03:58:19.458764', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (106, 1, 146, 1, NULL, NULL, '2025-12-17 03:58:19.458764', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (107, 1, 149, 1, NULL, NULL, '2025-12-17 03:58:19.458764', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (108, 2, 144, 1, NULL, NULL, '2025-12-17 03:58:19.458764', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (109, 2, 147, 1, NULL, NULL, '2025-12-17 03:58:19.458764', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (110, 2, 150, 1, NULL, NULL, '2025-12-17 03:58:19.458764', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (111, 3, 145, 1, NULL, NULL, '2025-12-17 03:58:19.458764', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (112, 3, 148, 1, NULL, NULL, '2025-12-17 03:58:19.458764', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (113, 3, 151, 1, NULL, NULL, '2025-12-17 03:58:19.458764', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (114, 4, 143, 1, NULL, NULL, '2025-12-17 03:58:19.458764', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (115, 5, 144, 1, NULL, NULL, '2025-12-17 03:58:19.458764', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (116, 6, 145, 1, NULL, NULL, '2025-12-17 03:58:19.458764', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (117, 1, 152, 0, NULL, NULL, '2025-12-17 05:14:16.421973', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (118, 1, 158, 0, NULL, NULL, '2025-12-17 05:14:16.421973', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (119, 1, 155, 0, NULL, NULL, '2025-12-17 05:14:16.421973', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (120, 2, 153, 0, NULL, NULL, '2025-12-17 05:14:16.421973', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (121, 2, 156, 0, NULL, NULL, '2025-12-17 05:14:16.421973', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (122, 2, 159, 0, NULL, NULL, '2025-12-17 05:14:16.421973', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (123, 3, 160, 0, NULL, NULL, '2025-12-17 05:14:16.421973', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (124, 3, 157, 0, NULL, NULL, '2025-12-17 05:14:16.421973', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (125, 3, 154, 0, NULL, NULL, '2025-12-17 05:14:16.421973', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (126, 4, 152, 0, NULL, NULL, '2025-12-17 05:14:16.421973', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (127, 5, 153, 0, NULL, NULL, '2025-12-17 05:14:16.421973', '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_role_permission" VALUES (128, 6, 154, 0, NULL, NULL, '2025-12-17 05:14:16.421973', '2025-12-17 05:14:16.421973');

-- ----------------------------
-- Auto increment value for sys_role_permission
-- ----------------------------
SELECT setval('"public"."sys_role_permission_id_seq"', 128, true);

-- ----------------------------
-- Indexes structure for table sys_role_permission
-- ----------------------------
CREATE INDEX "idx_sys_role_permission_is_deleted" ON "public"."sys_role_permission" USING btree (
  "is_deleted" "pg_catalog"."int2_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sys_role_permission_permission_id" ON "public"."sys_role_permission" USING btree (
  "permission_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sys_role_permission_role_id" ON "public"."sys_role_permission" USING btree (
  "role_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "uk_sys_role_permission" ON "public"."sys_role_permission" USING btree (
  "role_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  "permission_id" "pg_catalog"."int8_ops" ASC NULLS LAST
) WHERE is_deleted = 0;

-- ----------------------------
-- Primary Key structure for table sys_role_permission
-- ----------------------------
ALTER TABLE "public"."sys_role_permission" ADD CONSTRAINT "sys_role_permission_pkey" PRIMARY KEY ("id");
