/*
 Navicat Premium Dump SQL

 Source Server         : postgres
 Source Server Type    : PostgreSQL
 Source Server Version : 160010 (160010)
 Source Host           : localhost:5432
 Source Catalog        : sci-z-college
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160010 (160010)
 File Encoding         : 65001

 Date: 24/12/2025 10:06:42
*/


-- ----------------------------
-- Table structure for sys_permission
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_permission";
CREATE TABLE "public"."sys_permission" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "parent_id" int8 DEFAULT 0,
  "permission_name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "permission_code" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "permission_type" int2 NOT NULL,
  "industry_type" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "path" varchar(200) COLLATE "pg_catalog"."default",
  "component" varchar(200) COLLATE "pg_catalog"."default",
  "icon" varchar(100) COLLATE "pg_catalog"."default",
  "sort_order" int4 DEFAULT 0,
  "status" int2 DEFAULT 1,
  "is_deleted" int2 DEFAULT 0,
  "created_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "created_by" int8,
  "updated_by" int8,
  "updated_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "public"."sys_permission"."id" IS '权限ID，主键，自增';
COMMENT ON COLUMN "public"."sys_permission"."parent_id" IS '父权限ID，0表示顶级权限';
COMMENT ON COLUMN "public"."sys_permission"."permission_name" IS '权限名称';
COMMENT ON COLUMN "public"."sys_permission"."permission_code" IS '权限编码，唯一标识';
COMMENT ON COLUMN "public"."sys_permission"."permission_type" IS '权限类型：1=菜单，2=按钮，3=API';
COMMENT ON COLUMN "public"."sys_permission"."industry_type" IS '行业类型';
COMMENT ON COLUMN "public"."sys_permission"."path" IS '路由路径';
COMMENT ON COLUMN "public"."sys_permission"."component" IS '组件路径';
COMMENT ON COLUMN "public"."sys_permission"."icon" IS '图标';
COMMENT ON COLUMN "public"."sys_permission"."sort_order" IS '排序';
COMMENT ON COLUMN "public"."sys_permission"."status" IS '权限状态：1=启用，0=禁用';
COMMENT ON COLUMN "public"."sys_permission"."is_deleted" IS '逻辑删除标识：0=未删除，1=已删除';
COMMENT ON COLUMN "public"."sys_permission"."created_time" IS '创建时间';
COMMENT ON COLUMN "public"."sys_permission"."created_by" IS '创建人ID';
COMMENT ON COLUMN "public"."sys_permission"."updated_by" IS '更新人ID';
COMMENT ON COLUMN "public"."sys_permission"."updated_time" IS '更新时间';
COMMENT ON TABLE "public"."sys_permission" IS '系统权限表';

-- ----------------------------
-- Records of sys_permission
-- ----------------------------
INSERT INTO "public"."sys_permission" VALUES (1, 0, '仪表板', 'menu:dashboard:view', 1, 'education', '/dashboard', NULL, 'Odometer', 10, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (2, 0, '仪表板', 'menu:dashboard:view', 1, 'medical', '/dashboard', NULL, 'Odometer', 10, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (3, 0, '仪表板', 'menu:dashboard:view', 1, 'power', '/dashboard', NULL, 'Odometer', 10, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (4, 0, '申报管理', 'menu:declaration:list', 1, 'education', 'declaration', NULL, 'Document', 20, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (5, 0, '申报管理', 'menu:declaration:list', 1, 'medical', 'declaration', NULL, 'Document', 20, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (6, 0, '申报管理', 'menu:declaration:list', 1, 'power', 'declaration', NULL, 'Document', 20, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (7, 0, '项目管理', 'menu:project:list', 1, 'education', 'project', NULL, 'Folder', 30, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (8, 0, '项目管理', 'menu:project:list', 1, 'medical', 'project', NULL, 'Folder', 30, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (9, 0, '项目管理', 'menu:project:list', 1, 'power', 'project', NULL, 'Folder', 30, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (10, 0, '验收管理', 'menu:report:list', 1, 'education', 'acceptance', NULL, 'Check', 40, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (11, 0, '验收管理', 'menu:report:list', 1, 'medical', 'acceptance', NULL, 'Check', 40, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (12, 0, '验收管理', 'menu:report:list', 1, 'power', 'acceptance', NULL, 'Check', 40, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (13, 0, 'AI助手', 'menu:ai:chat', 1, 'education', 'ai', NULL, 'Monitor', 50, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (14, 0, 'AI助手', 'menu:ai:chat', 1, 'medical', 'ai', NULL, 'Monitor', 50, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (15, 0, 'AI助手', 'menu:ai:chat', 1, 'power', 'ai', NULL, 'Monitor', 50, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (16, 0, '用户中心', 'menu:user:profile', 1, 'education', 'user', NULL, 'User', 60, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (17, 0, '用户中心', 'menu:user:profile', 1, 'medical', 'user', NULL, 'User', 60, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (18, 0, '用户中心', 'menu:user:profile', 1, 'power', 'user', NULL, 'User', 60, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (19, 0, '系统管理', 'menu:system:user', 1, 'education', 'system', NULL, 'Setting', 70, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (20, 0, '系统管理', 'menu:system:user', 1, 'medical', 'system', NULL, 'Setting', 70, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (21, 0, '系统管理', 'menu:system:user', 1, 'power', 'system', NULL, 'Setting', 70, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (22, 4, '申报列表', 'menu:declaration:list:sub', 1, 'education', '/declaration/list', NULL, 'List', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (23, 5, '申报列表', 'menu:declaration:list:sub', 1, 'medical', '/declaration/list', NULL, 'List', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (24, 6, '申报列表', 'menu:declaration:list:sub', 1, 'power', '/declaration/list', NULL, 'List', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (25, 4, '新建申报', 'menu:declaration:create', 1, 'education', '/declaration/create', NULL, 'CirclePlus', 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (26, 5, '新建申报', 'menu:declaration:create', 1, 'medical', '/declaration/create', NULL, 'CirclePlus', 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (27, 6, '新建申报', 'menu:declaration:create', 1, 'power', '/declaration/create', NULL, 'CirclePlus', 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (28, 7, '项目列表', 'menu:project:list:sub', 1, 'education', '/project/list', NULL, 'List', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (29, 8, '项目列表', 'menu:project:list:sub', 1, 'medical', '/project/list', NULL, 'List', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (30, 9, '项目列表', 'menu:project:list:sub', 1, 'power', '/project/list', NULL, 'List', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (31, 10, '报告管理', 'menu:report:list:sub', 1, 'education', '/report/list', NULL, 'List', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (32, 11, '报告管理', 'menu:report:list:sub', 1, 'medical', '/report/list', NULL, 'List', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (33, 12, '报告管理', 'menu:report:list:sub', 1, 'power', '/report/list', NULL, 'List', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (34, 13, '知识库', 'menu:knowledge:list', 1, 'education', '/knowledge/list', NULL, 'Reading', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (35, 14, '知识库', 'menu:knowledge:list', 1, 'medical', '/knowledge/list', NULL, 'Reading', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (36, 15, '知识库', 'menu:knowledge:list', 1, 'power', '/knowledge/list', NULL, 'Reading', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (37, 13, 'AI对话', 'menu:ai:chat:sub', 1, 'education', '/ai/chat', NULL, 'Avatar', 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (38, 14, 'AI对话', 'menu:ai:chat:sub', 1, 'medical', '/ai/chat', NULL, 'Avatar', 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (39, 15, 'AI对话', 'menu:ai:chat:sub', 1, 'power', '/ai/chat', NULL, 'Avatar', 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (40, 16, '个人信息', 'menu:user:profile:sub', 1, 'education', '/user/profile', NULL, 'House', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (41, 17, '个人信息', 'menu:user:profile:sub', 1, 'medical', '/user/profile', NULL, 'House', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (42, 18, '个人信息', 'menu:user:profile:sub', 1, 'power', '/user/profile', NULL, 'House', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (43, 16, '安全设置', 'menu:user:security', 1, 'education', '/user/security', NULL, 'Lock', 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (44, 17, '安全设置', 'menu:user:security', 1, 'medical', '/user/security', NULL, 'Lock', 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (45, 18, '安全设置', 'menu:user:security', 1, 'power', '/user/security', NULL, 'Lock', 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (46, 19, '用户管理', 'menu:system:user:sub', 1, 'education', '/system/user', NULL, 'User', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (47, 20, '用户管理', 'menu:system:user:sub', 1, 'medical', '/system/user', NULL, 'User', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (48, 21, '用户管理', 'menu:system:user:sub', 1, 'power', '/system/user', NULL, 'User', 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (49, 19, '角色权限', 'menu:system:role', 1, 'education', '/system/role', NULL, 'Key', 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (50, 20, '角色权限', 'menu:system:role', 1, 'medical', '/system/role', NULL, 'Key', 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (51, 21, '角色权限', 'menu:system:role', 1, 'power', '/system/role', NULL, 'Key', 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (52, 19, '系统配置', 'menu:system:config', 1, 'education', '/system/config', NULL, 'Setting', 3, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (53, 20, '系统配置', 'menu:system:config', 1, 'medical', '/system/config', NULL, 'Setting', 3, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (54, 21, '系统配置', 'menu:system:config', 1, 'power', '/system/config', NULL, 'Setting', 3, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (55, 19, '日志管理', 'menu:system:logs', 1, 'education', '/system/logs', NULL, 'Document', 4, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (56, 20, '日志管理', 'menu:system:logs', 1, 'medical', '/system/logs', NULL, 'Document', 4, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (57, 21, '日志管理', 'menu:system:logs', 1, 'power', '/system/logs', NULL, 'Document', 4, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (58, 1, '仪表板-新建申报', 'button:dashboard:create_declaration', 2, 'education', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (59, 2, '仪表板-新建申报', 'button:dashboard:create_declaration', 2, 'medical', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (60, 3, '仪表板-新建申报', 'button:dashboard:create_declaration', 2, 'power', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (61, 4, '申报-新建按钮', 'button:declaration:create', 2, 'education', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (62, 5, '申报-新建按钮', 'button:declaration:create', 2, 'medical', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (63, 6, '申报-新建按钮', 'button:declaration:create', 2, 'power', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (64, 4, '申报-删除按钮', 'button:declaration:delete', 2, 'education', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (65, 5, '申报-删除按钮', 'button:declaration:delete', 2, 'medical', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (66, 6, '申报-删除按钮', 'button:declaration:delete', 2, 'power', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (67, 7, '项目-编辑按钮', 'button:project:edit', 2, 'education', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (68, 8, '项目-编辑按钮', 'button:project:edit', 2, 'medical', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (69, 9, '项目-编辑按钮', 'button:project:edit', 2, 'power', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (70, 7, '项目-删除按钮', 'button:project:delete', 2, 'education', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (71, 8, '项目-删除按钮', 'button:project:delete', 2, 'medical', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (72, 9, '项目-删除按钮', 'button:project:delete', 2, 'power', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (73, 10, '报告-删除按钮', 'button:report:delete', 2, 'education', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (74, 11, '报告-删除按钮', 'button:report:delete', 2, 'medical', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (75, 12, '报告-删除按钮', 'button:report:delete', 2, 'power', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (76, 10, '报告-验收按钮', 'button:report:accept', 2, 'education', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (77, 11, '报告-验收按钮', 'button:report:accept', 2, 'medical', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (78, 12, '报告-验收按钮', 'button:report:accept', 2, 'power', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (79, 46, '用户-新建按钮', 'button:user:create', 2, 'education', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (80, 47, '用户-新建按钮', 'button:user:create', 2, 'medical', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (81, 48, '用户-新建按钮', 'button:user:create', 2, 'power', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (82, 46, '用户-禁用按钮', 'button:user:disable', 2, 'education', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (83, 47, '用户-禁用按钮', 'button:user:disable', 2, 'medical', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (84, 48, '用户-禁用按钮', 'button:user:disable', 2, 'power', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (85, 46, '用户-删除按钮', 'button:user:delete', 2, 'education', NULL, NULL, NULL, 3, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (86, 47, '用户-删除按钮', 'button:user:delete', 2, 'medical', NULL, NULL, NULL, 3, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (87, 48, '用户-删除按钮', 'button:user:delete', 2, 'power', NULL, NULL, NULL, 3, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (88, 49, '角色-新建按钮', 'button:role:create', 2, 'education', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (89, 50, '角色-新建按钮', 'button:role:create', 2, 'medical', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (90, 51, '角色-新建按钮', 'button:role:create', 2, 'power', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (91, 49, '角色-编辑按钮', 'button:role:edit', 2, 'education', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (92, 50, '角色-编辑按钮', 'button:role:edit', 2, 'medical', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (93, 51, '角色-编辑按钮', 'button:role:edit', 2, 'power', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (94, 49, '角色-配置权限按钮', 'button:role:config', 2, 'education', NULL, NULL, NULL, 3, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (95, 50, '角色-配置权限按钮', 'button:role:config', 2, 'medical', NULL, NULL, NULL, 3, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (96, 51, '角色-配置权限按钮', 'button:role:config', 2, 'power', NULL, NULL, NULL, 3, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (97, 49, '角色-删除按钮', 'button:role:delete', 2, 'education', NULL, NULL, NULL, 4, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (98, 50, '角色-删除按钮', 'button:role:delete', 2, 'medical', NULL, NULL, NULL, 4, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (99, 51, '角色-删除按钮', 'button:role:delete', 2, 'power', NULL, NULL, NULL, 4, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (100, 55, '日志-清空按钮', 'button:log:clear', 2, 'education', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (101, 56, '日志-清空按钮', 'button:log:clear', 2, 'medical', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (102, 57, '日志-清空按钮', 'button:log:clear', 2, 'power', NULL, NULL, NULL, 1, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (103, 55, '日志-导出按钮', 'button:log:export', 2, 'education', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (104, 56, '日志-导出按钮', 'button:log:export', 2, 'medical', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (105, 57, '日志-导出按钮', 'button:log:export', 2, 'power', NULL, NULL, NULL, 2, 1, 0, '2025-11-11 05:13:15.757462', NULL, NULL, '2025-11-11 05:13:15.757462');
INSERT INTO "public"."sys_permission" VALUES (106, 19, 'API Key 配置', 'menu:system:apikey', 1, 'education', '/system/apikey', NULL, 'Key', 5, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (107, 20, 'API Key 配置', 'menu:system:apikey', 1, 'medical', '/system/apikey', NULL, 'Key', 5, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (108, 21, 'API Key 配置', 'menu:system:apikey', 1, 'power', '/system/apikey', NULL, 'Key', 5, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (109, 106, 'API Key-新建按钮', 'button:apikey:create', 2, 'education', NULL, NULL, NULL, 1, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (110, 107, 'API Key-新建按钮', 'button:apikey:create', 2, 'medical', NULL, NULL, NULL, 1, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (111, 108, 'API Key-新建按钮', 'button:apikey:create', 2, 'power', NULL, NULL, NULL, 1, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (112, 106, 'API Key-编辑按钮', 'button:apikey:edit', 2, 'education', NULL, NULL, NULL, 2, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (113, 107, 'API Key-编辑按钮', 'button:apikey:edit', 2, 'medical', NULL, NULL, NULL, 2, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (114, 108, 'API Key-编辑按钮', 'button:apikey:edit', 2, 'power', NULL, NULL, NULL, 2, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (115, 106, 'API Key-删除按钮', 'button:apikey:delete', 2, 'education', NULL, NULL, NULL, 3, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (116, 107, 'API Key-删除按钮', 'button:apikey:delete', 2, 'medical', NULL, NULL, NULL, 3, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (117, 108, 'API Key-删除按钮', 'button:apikey:delete', 2, 'power', NULL, NULL, NULL, 3, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (118, 106, 'API Key-启用/禁用按钮', 'button:apikey:toggle', 2, 'education', NULL, NULL, NULL, 4, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (119, 107, 'API Key-启用/禁用按钮', 'button:apikey:toggle', 2, 'medical', NULL, NULL, NULL, 4, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (120, 108, 'API Key-启用/禁用按钮', 'button:apikey:toggle', 2, 'power', NULL, NULL, NULL, 4, 1, 0, '2025-11-21 01:45:23.784258', NULL, NULL, '2025-11-21 01:45:23.784258');
INSERT INTO "public"."sys_permission" VALUES (121, 10, '报告生成', 'menu:report:generate', 1, 'education', '/report/generate', NULL, 'Edit', 2, 1, 0, '2025-11-25 03:40:45.387141', NULL, NULL, '2025-11-25 03:40:45.387141');
INSERT INTO "public"."sys_permission" VALUES (122, 13, '文献搜索', 'menu:literature:search', 1, 'education', '/literature/search', 'literature/search', 'Search', 3, 1, 1, '2025-12-16 08:17:15.400399', NULL, NULL, '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_permission" VALUES (123, 14, '文献搜索', 'menu:literature:search', 1, 'medical', '/literature/search', 'literature/search', 'Search', 3, 1, 1, '2025-12-16 08:17:15.400399', NULL, NULL, '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_permission" VALUES (124, 15, '文献搜索', 'menu:literature:search', 1, 'power', '/literature/search', 'literature/search', 'Search', 3, 1, 1, '2025-12-16 08:17:15.400399', NULL, NULL, '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_permission" VALUES (125, 122, '文献搜索-搜索按钮', 'button:literature:search', 2, 'education', NULL, NULL, NULL, 1, 1, 1, '2025-12-16 08:17:15.400399', NULL, NULL, '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_permission" VALUES (126, 123, '文献搜索-搜索按钮', 'button:literature:search', 2, 'medical', NULL, NULL, NULL, 1, 1, 1, '2025-12-16 08:17:15.400399', NULL, NULL, '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_permission" VALUES (127, 124, '文献搜索-搜索按钮', 'button:literature:search', 2, 'power', NULL, NULL, NULL, 1, 1, 1, '2025-12-16 08:17:15.400399', NULL, NULL, '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_permission" VALUES (128, 122, '文献搜索-查看详情按钮', 'button:literature:detail', 2, 'education', NULL, NULL, NULL, 2, 1, 1, '2025-12-16 08:17:15.400399', NULL, NULL, '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_permission" VALUES (129, 123, '文献搜索-查看详情按钮', 'button:literature:detail', 2, 'medical', NULL, NULL, NULL, 2, 1, 1, '2025-12-16 08:17:15.400399', NULL, NULL, '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_permission" VALUES (130, 124, '文献搜索-查看详情按钮', 'button:literature:detail', 2, 'power', NULL, NULL, NULL, 2, 1, 1, '2025-12-16 08:17:15.400399', NULL, NULL, '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_permission" VALUES (131, 0, '学术搜索', 'menu:academic:search', 1, 'education', '/academic', NULL, 'Search', 45, 1, 0, '2025-12-17 03:28:26.625994', NULL, NULL, '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_permission" VALUES (132, 0, '学术搜索', 'menu:academic:search', 1, 'medical', '/academic', NULL, 'Search', 45, 1, 0, '2025-12-17 03:28:26.625994', NULL, NULL, '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_permission" VALUES (133, 0, '学术搜索', 'menu:academic:search', 1, 'power', '/academic', NULL, 'Search', 45, 1, 0, '2025-12-17 03:28:26.625994', NULL, NULL, '2025-12-17 03:28:26.625994');
INSERT INTO "public"."sys_permission" VALUES (134, 131, '文献搜索', 'menu:literature:search', 1, 'education', '/literature/search', 'literature/search', 'Document', 1, 1, 1, '2025-12-17 03:28:26.625994', NULL, NULL, '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_permission" VALUES (135, 132, '文献搜索', 'menu:literature:search', 1, 'medical', '/literature/search', 'literature/search', 'Document', 1, 1, 1, '2025-12-17 03:28:26.625994', NULL, NULL, '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_permission" VALUES (136, 133, '文献搜索', 'menu:literature:search', 1, 'power', '/literature/search', 'literature/search', 'Document', 1, 1, 1, '2025-12-17 03:28:26.625994', NULL, NULL, '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_permission" VALUES (137, 134, '文献搜索-搜索按钮', 'button:literature:search', 2, 'education', NULL, NULL, NULL, 1, 1, 1, '2025-12-17 03:28:26.625994', NULL, NULL, '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_permission" VALUES (138, 135, '文献搜索-搜索按钮', 'button:literature:search', 2, 'medical', NULL, NULL, NULL, 1, 1, 1, '2025-12-17 03:28:26.625994', NULL, NULL, '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_permission" VALUES (139, 136, '文献搜索-搜索按钮', 'button:literature:search', 2, 'power', NULL, NULL, NULL, 1, 1, 1, '2025-12-17 03:28:26.625994', NULL, NULL, '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_permission" VALUES (140, 134, '文献搜索-查看详情按钮', 'button:literature:detail', 2, 'education', NULL, NULL, NULL, 2, 1, 1, '2025-12-17 03:28:26.625994', NULL, NULL, '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_permission" VALUES (141, 135, '文献搜索-查看详情按钮', 'button:literature:detail', 2, 'medical', NULL, NULL, NULL, 2, 1, 1, '2025-12-17 03:28:26.625994', NULL, NULL, '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_permission" VALUES (142, 136, '文献搜索-查看详情按钮', 'button:literature:detail', 2, 'power', NULL, NULL, NULL, 2, 1, 1, '2025-12-17 03:28:26.625994', NULL, NULL, '2025-12-17 03:58:19.458764');
INSERT INTO "public"."sys_permission" VALUES (143, 131, '文献搜索', 'menu:literature:search', 1, 'education', '/literature/search', 'literature/search', 'Document', 1, 1, 1, '2025-12-17 03:58:19.458764', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (144, 132, '文献搜索', 'menu:literature:search', 1, 'medical', '/literature/search', 'literature/search', 'Document', 1, 1, 1, '2025-12-17 03:58:19.458764', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (145, 133, '文献搜索', 'menu:literature:search', 1, 'power', '/literature/search', 'literature/search', 'Document', 1, 1, 1, '2025-12-17 03:58:19.458764', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (146, 143, '文献搜索-搜索按钮', 'button:literature:search', 2, 'education', NULL, NULL, NULL, 1, 1, 1, '2025-12-17 03:58:19.458764', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (147, 144, '文献搜索-搜索按钮', 'button:literature:search', 2, 'medical', NULL, NULL, NULL, 1, 1, 1, '2025-12-17 03:58:19.458764', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (148, 145, '文献搜索-搜索按钮', 'button:literature:search', 2, 'power', NULL, NULL, NULL, 1, 1, 1, '2025-12-17 03:58:19.458764', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (149, 143, '文献搜索-查看详情按钮', 'button:literature:detail', 2, 'education', NULL, NULL, NULL, 2, 1, 1, '2025-12-17 03:58:19.458764', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (150, 144, '文献搜索-查看详情按钮', 'button:literature:detail', 2, 'medical', NULL, NULL, NULL, 2, 1, 1, '2025-12-17 03:58:19.458764', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (151, 145, '文献搜索-查看详情按钮', 'button:literature:detail', 2, 'power', NULL, NULL, NULL, 2, 1, 1, '2025-12-17 03:58:19.458764', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (152, 131, '文献搜索', 'menu:literature:search', 1, 'education', '/literature/search', 'literature/search', 'Document', 1, 1, 0, '2025-12-17 05:14:16.421973', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (153, 132, '文献搜索', 'menu:literature:search', 1, 'medical', '/literature/search', 'literature/search', 'Document', 1, 1, 0, '2025-12-17 05:14:16.421973', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (154, 133, '文献搜索', 'menu:literature:search', 1, 'power', '/literature/search', 'literature/search', 'Document', 1, 1, 0, '2025-12-17 05:14:16.421973', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (155, 152, '文献搜索-搜索按钮', 'button:literature:search', 2, 'education', NULL, NULL, NULL, 1, 1, 0, '2025-12-17 05:14:16.421973', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (156, 153, '文献搜索-搜索按钮', 'button:literature:search', 2, 'medical', NULL, NULL, NULL, 1, 1, 0, '2025-12-17 05:14:16.421973', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (157, 154, '文献搜索-搜索按钮', 'button:literature:search', 2, 'power', NULL, NULL, NULL, 1, 1, 0, '2025-12-17 05:14:16.421973', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (158, 152, '文献搜索-查看详情按钮', 'button:literature:detail', 2, 'education', NULL, NULL, NULL, 2, 1, 0, '2025-12-17 05:14:16.421973', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (159, 153, '文献搜索-查看详情按钮', 'button:literature:detail', 2, 'medical', NULL, NULL, NULL, 2, 1, 0, '2025-12-17 05:14:16.421973', NULL, NULL, '2025-12-17 05:14:16.421973');
INSERT INTO "public"."sys_permission" VALUES (160, 154, '文献搜索-查看详情按钮', 'button:literature:detail', 2, 'power', NULL, NULL, NULL, 2, 1, 0, '2025-12-17 05:14:16.421973', NULL, NULL, '2025-12-17 05:14:16.421973');

-- ----------------------------
-- Auto increment value for sys_permission
-- ----------------------------
SELECT setval('"public"."sys_permission_id_seq"', 160, true);

-- ----------------------------
-- Indexes structure for table sys_permission
-- ----------------------------
CREATE INDEX "idx_sys_permission_industry_type" ON "public"."sys_permission" USING btree (
  "industry_type" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sys_permission_is_deleted" ON "public"."sys_permission" USING btree (
  "is_deleted" "pg_catalog"."int2_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sys_permission_parent_id" ON "public"."sys_permission" USING btree (
  "parent_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sys_permission_sort_order" ON "public"."sys_permission" USING btree (
  "sort_order" "pg_catalog"."int4_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sys_permission_status" ON "public"."sys_permission" USING btree (
  "status" "pg_catalog"."int2_ops" ASC NULLS LAST
);
CREATE INDEX "idx_sys_permission_type" ON "public"."sys_permission" USING btree (
  "permission_type" "pg_catalog"."int2_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "uk_sys_permission_code_industry" ON "public"."sys_permission" USING btree (
  "permission_code" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "industry_type" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE is_deleted = 0;

-- ----------------------------
-- Primary Key structure for table sys_permission
-- ----------------------------
ALTER TABLE "public"."sys_permission" ADD CONSTRAINT "sys_permission_pkey" PRIMARY KEY ("id");
