-- ******************************************************
-- 站内消息表 sys_message
-- 用于产教研分发通知、接受/拒绝结果及后续系统通知
-- 风格与 init_all_tables.sql 保持一致：PostgreSQL、BIGINT 自增、is_deleted、created_by/updated_by、COMMENT、索引
-- ******************************************************

CREATE TABLE IF NOT EXISTS sys_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    sender_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    extra_json TEXT,
    status VARCHAR(20) DEFAULT 'pending',
    read_time TIMESTAMP,
    is_deleted SMALLINT DEFAULT 0,
    created_by BIGINT,
    updated_by BIGINT,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sys_message IS '站内消息表';
COMMENT ON COLUMN sys_message.id IS '消息ID，主键，自增';
COMMENT ON COLUMN sys_message.type IS '消息类型：industry_education_distribute=产教研分发，system_notice=系统通知等';
COMMENT ON COLUMN sys_message.sender_id IS '发送人用户ID';
COMMENT ON COLUMN sys_message.receiver_id IS '接收人用户ID';
COMMENT ON COLUMN sys_message.title IS '消息标题';
COMMENT ON COLUMN sys_message.content IS '消息正文';
COMMENT ON COLUMN sys_message.extra_json IS '扩展数据(JSON)：如 topic_label、target_team_id、reject_reason、declaration_id、project_id 等';
COMMENT ON COLUMN sys_message.status IS '状态：pending=待处理/未读，read=已读，accepted=已接受，rejected=已拒绝';
COMMENT ON COLUMN sys_message.read_time IS '已读时间';
COMMENT ON COLUMN sys_message.is_deleted IS '逻辑删除标识：0=未删除，1=已删除';
COMMENT ON COLUMN sys_message.created_by IS '创建人ID';
COMMENT ON COLUMN sys_message.updated_by IS '更新人ID';
COMMENT ON COLUMN sys_message.created_time IS '创建时间';
COMMENT ON COLUMN sys_message.updated_time IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_sys_message_receiver_id ON sys_message(receiver_id);
CREATE INDEX IF NOT EXISTS idx_sys_message_sender_id ON sys_message(sender_id);
CREATE INDEX IF NOT EXISTS idx_sys_message_status ON sys_message(status);
CREATE INDEX IF NOT EXISTS idx_sys_message_created_time ON sys_message(created_time DESC);
CREATE INDEX IF NOT EXISTS idx_sys_message_is_deleted ON sys_message(is_deleted);
CREATE INDEX IF NOT EXISTS idx_sys_message_receiver_unread ON sys_message(receiver_id, is_deleted) WHERE status = 'pending';
