-- ******************************************************
-- Sci-Z Platform - Migration
-- Version: V20241112_01
-- Purpose: Industry-specific user profile field templates
-- ******************************************************

BEGIN;

-- =============== 用户扩展字段模板表 ===============
CREATE TABLE IF NOT EXISTS sys_profile_field (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    industry_type VARCHAR(50) NOT NULL,
    field_code VARCHAR(50) NOT NULL,
    field_label VARCHAR(100) NOT NULL,
    field_type VARCHAR(20) NOT NULL,
    description VARCHAR(255),
    is_required SMALLINT DEFAULT 0,
    is_enabled SMALLINT DEFAULT 1,
    sort_order INT DEFAULT 0,
    is_deleted SMALLINT DEFAULT 0,
    created_by BIGINT,
    updated_by BIGINT,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sys_profile_field IS '用户扩展字段模板表';
COMMENT ON COLUMN sys_profile_field.id IS '模板ID，主键，自增';
COMMENT ON COLUMN sys_profile_field.industry_type IS '行业类型(education/medical/power)';
COMMENT ON COLUMN sys_profile_field.field_code IS '字段编码(唯一)';
COMMENT ON COLUMN sys_profile_field.field_label IS '字段展示名称';
COMMENT ON COLUMN sys_profile_field.field_type IS '字段类型(text/select/number/date)';
COMMENT ON COLUMN sys_profile_field.description IS '字段描述';
COMMENT ON COLUMN sys_profile_field.is_required IS '是否必填(0:否,1:是)';
COMMENT ON COLUMN sys_profile_field.is_enabled IS '是否启用(0:禁用,1:启用)';
COMMENT ON COLUMN sys_profile_field.sort_order IS '排序号';
COMMENT ON COLUMN sys_profile_field.is_deleted IS '逻辑删除标识：0=未删除，1=已删除';
COMMENT ON COLUMN sys_profile_field.created_by IS '创建人ID';
COMMENT ON COLUMN sys_profile_field.updated_by IS '更新人ID';
COMMENT ON COLUMN sys_profile_field.created_time IS '创建时间';
COMMENT ON COLUMN sys_profile_field.updated_time IS '更新时间';
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_profile_field_code
    ON sys_profile_field(industry_type, field_code)
    WHERE is_deleted = 0;
CREATE INDEX IF NOT EXISTS idx_sys_profile_field_industry
    ON sys_profile_field(industry_type);

-- =============== 用户扩展字段选项表 ===============
CREATE TABLE IF NOT EXISTS sys_profile_field_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id BIGINT NOT NULL,
    option_value VARCHAR(100) NOT NULL,
    option_label VARCHAR(100) NOT NULL,
    sort_order INT DEFAULT 0,
    is_default SMALLINT DEFAULT 0,
    is_deleted SMALLINT DEFAULT 0,
    created_by BIGINT,
    updated_by BIGINT,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sys_profile_field_option IS '用户扩展字段选项表';
COMMENT ON COLUMN sys_profile_field_option.id IS '选项ID，主键，自增';
COMMENT ON COLUMN sys_profile_field_option.field_id IS '所属字段ID';
COMMENT ON COLUMN sys_profile_field_option.option_value IS '选项值';
COMMENT ON COLUMN sys_profile_field_option.option_label IS '选项展示名';
COMMENT ON COLUMN sys_profile_field_option.sort_order IS '排序号';
COMMENT ON COLUMN sys_profile_field_option.is_default IS '是否默认选项(0:否,1:是)';
COMMENT ON COLUMN sys_profile_field_option.is_deleted IS '逻辑删除标识：0=未删除，1=已删除';
COMMENT ON COLUMN sys_profile_field_option.created_by IS '创建人ID';
COMMENT ON COLUMN sys_profile_field_option.updated_by IS '更新人ID';
COMMENT ON COLUMN sys_profile_field_option.created_time IS '创建时间';
COMMENT ON COLUMN sys_profile_field_option.updated_time IS '更新时间';
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_profile_option_value
    ON sys_profile_field_option(field_id, option_value)
    WHERE is_deleted = 0;
CREATE INDEX IF NOT EXISTS idx_sys_profile_option_field
    ON sys_profile_field_option(field_id);

-- =============== 初始化字段模板：教育行业 - 职称 ===============
INSERT INTO sys_profile_field (industry_type, field_code, field_label, field_type, description,
                               is_required, is_enabled, sort_order)
SELECT 'education', 'title', '职称', 'select', '教育行业职称字段', 0, 1, 10
WHERE NOT EXISTS (
    SELECT 1 FROM sys_profile_field
    WHERE industry_type = 'education' AND field_code = 'title' AND is_deleted = 0
);

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'assistant', '助教', 1, 0
FROM sys_profile_field field
WHERE field.industry_type = 'education'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'assistant' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'lecturer', '讲师', 2, 0
FROM sys_profile_field field
WHERE field.industry_type = 'education'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'lecturer' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'senior_lecturer', '高级讲师', 3, 0
FROM sys_profile_field field
WHERE field.industry_type = 'education'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'senior_lecturer' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'associate_professor', '副教授', 4, 0
FROM sys_profile_field field
WHERE field.industry_type = 'education'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'associate_professor' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'professor', '教授', 5, 0
FROM sys_profile_field field
WHERE field.industry_type = 'education'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'professor' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'distinguished_professor', '特聘教授', 6, 1
FROM sys_profile_field field
WHERE field.industry_type = 'education'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'distinguished_professor' AND opt.is_deleted = 0
    );

-- =============== 初始化字段模板：医疗行业 - 职称 ===============
INSERT INTO sys_profile_field (industry_type, field_code, field_label, field_type, description,
                               is_required, is_enabled, sort_order)
SELECT 'medical', 'title', '职称', 'select', '医疗行业职称字段', 0, 1, 10
WHERE NOT EXISTS (
    SELECT 1 FROM sys_profile_field
    WHERE industry_type = 'medical' AND field_code = 'title' AND is_deleted = 0
);

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'resident', '住院医师', 1, 0
FROM sys_profile_field field
WHERE field.industry_type = 'medical'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'resident' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'attending', '主治医师', 2, 0
FROM sys_profile_field field
WHERE field.industry_type = 'medical'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'attending' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'assistant_chief', '主治副主任', 3, 0
FROM sys_profile_field field
WHERE field.industry_type = 'medical'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'assistant_chief' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'deputy_chief', '副主任医师', 4, 0
FROM sys_profile_field field
WHERE field.industry_type = 'medical'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'deputy_chief' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'chief', '主任医师', 5, 1
FROM sys_profile_field field
WHERE field.industry_type = 'medical'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'chief' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'specialist', '特聘专家', 6, 0
FROM sys_profile_field field
WHERE field.industry_type = 'medical'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'specialist' AND opt.is_deleted = 0
    );

-- =============== 初始化字段模板：电力行业 - 职称 ===============
INSERT INTO sys_profile_field (industry_type, field_code, field_label, field_type, description,
                               is_required, is_enabled, sort_order)
SELECT 'power', 'title', '职称', 'select', '电力行业职称字段', 0, 1, 10
WHERE NOT EXISTS (
    SELECT 1 FROM sys_profile_field
    WHERE industry_type = 'power' AND field_code = 'title' AND is_deleted = 0
);

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'assistant_engineer', '助理工程师', 1, 0
FROM sys_profile_field field
WHERE field.industry_type = 'power'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'assistant_engineer' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'engineer', '工程师', 2, 0
FROM sys_profile_field field
WHERE field.industry_type = 'power'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'engineer' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'technician', '技术员', 3, 0
FROM sys_profile_field field
WHERE field.industry_type = 'power'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'technician' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'senior_engineer', '高级工程师', 4, 0
FROM sys_profile_field field
WHERE field.industry_type = 'power'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'senior_engineer' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'chief_engineer', '正高级工程师', 5, 0
FROM sys_profile_field field
WHERE field.industry_type = 'power'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'chief_engineer' AND opt.is_deleted = 0
    );

INSERT INTO sys_profile_field_option (field_id, option_value, option_label, sort_order, is_default)
SELECT field.id, 'chief_engineer_special', '首席工程师', 6, 1
FROM sys_profile_field field
WHERE field.industry_type = 'power'
  AND field.field_code = 'title'
  AND field.is_deleted = 0
  AND NOT EXISTS (
        SELECT 1 FROM sys_profile_field_option opt
        WHERE opt.field_id = field.id AND opt.option_value = 'chief_engineer_special' AND opt.is_deleted = 0
    );

COMMIT;


